version: '2'
services:

  app:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db/storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dialogue_db
      MYSQL_DATABASE: core
      MYSQL_ROOT_HOST: 172.19.0.1